when@prod:
  sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
      # Add request headers, cookies, IP address and the authenticated user
      # see https://docs.sentry.io/platforms/php/data-management/data-collected/ for more info
      # send_default_pii: true
      ignore_exceptions:
        - 'Symfony\Component\ErrorHandler\Error\FatalError'
        - 'Symfony\Component\Debug\Exception\FatalErrorException'
      release: '%opencal_version%'

      environment: "%kernel.environment%"

  monolog:
    handlers:
      sentry:
        type: sentry
        level: !php/const Monolog\Logger::ERROR
        hub_id: Sentry\State\HubInterface
        fill_extra_context: true # Enables sending monolog context to Sentry
        process_psr_3_messages: false # Disables the resolution of PSR-3 placeholders
